### ISSUE TITLE
invalid_auth

### ISSUE THREAD

**Issue by 154pinkchairs** [kohbis/rslack#146]
Using rslack 0.2.5 on macos 13.1, I've installed the application to my workspace with the necessary permissions and added my OAUTH token as $RSLACK_TOKEN to my zshrc and then sourced it. But when I run `rslack` I got `invalid_auth`. Shouldn't I also add some env vars like Client Secret, Client ID or Verification Token? And how do I name these if so? I've also tried writing the token as an unquoted string to a .token file in `/opt/homebrew/Cellar/rslack/v0.2.5`.

**Comment by kohbis** [comment]
Hi @154pinkchairs !

Thanks for your reporting !
I found a problem with the method of passing the new token...

I fixed in #148 and release new version `v0.2.6` (also homebrew)
